#!/bin/bash
# $Id: newt3_load_module,v 1.4 2004/11/03 06:19:49 bettin Exp $
echo "INIZIO 0"
module="new_t3_main"
device="new_t3_main"
mode="664"

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi
echo "INIZIO 1"
# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
/sbin/insmod ./$module.ko $* || exit 1
echo "INIZIO 2"
# retrieve $major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
echo "INIZIO $major"
# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm -f /dev/${device}[0-3]
echo "INIZIO 01"
mknod /dev/${device}0 c 249 0
echo "mknod /dev/${device}1 c $major 1"
mknod /dev/${device}1 c 249 1
echo "INIZIO 03"
mknod /dev/${device}2 c 249 2
echo "INIZIO 04"
mknod /dev/${device}3 c 249 3
echo "INIZIO 05"
ln -sf ${device}0 /dev/${device}
echo "INIZIO 06"
chgrp $group /dev/${device}[0-3] 
echo "INIZIO 07"
chmod $mode  /dev/${device}[0-3]



